In [155]:
import pandas as pd 
import numpy as np 
import xgboost
import os
import time
import warnings
import sklearn
import seaborn as sns 
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
import matplotlib.pyplot as plt 
import datetime
%matplotlib inline
warnings.filterwarnings('ignore')

In [156]:
file=r'c:/users/lance/desktop/GitHub_project/tianchi_power_data/matrix_0.csv'
weatherfile=r'c:/users/lance/desktop/GitHub_project/tianchi_power_data/weather_data_2014-1-1~2016~9-30.xlsx'
numst='sum'

In [157]:
data=pd.read_csv(file)
weatherdata=pd.read_excel(weatherfile)
data=data.set_index('Unnamed: 0')
k=[str(x) for x in range(1,1455)]
k.append('sum')
data.columns=k
weatherdata=weatherdata.set_index('date')

def tz(df,str1):
    df['timestamp']=df.index
    df['time_stamp']=pd.DataFrame(pd.to_datetime(df['timestamp']))
    df['dow'] = df.time_stamp.apply(lambda x: x.dayofweek)
    df['doy'] = df.time_stamp.apply(lambda x: x.dayofyear)
    df['day'] = df.time_stamp.apply(lambda x: x.day)
    df['month'] = df.time_stamp.apply(lambda x: x.month)
    df['d-1']=df[str1].shift(1)
    df['d-2']=df[str1].shift(2)
    df['d_dif']=df['d-1']-df['d-2']
    weatherdata['date']=weatherdata.index
    combineddf=pd.merge(left=df,right=weatherdata,left_on='time_stamp',right_on='date',how='left')
    combineddf=combineddf.fillna(0)
    return combineddf

combineddf=tz(pd.DataFrame(data[numst]),numst)
combineddf=combineddf.set_index('time_stamp')

X=combineddf[['dow','doy','day','month','d-1','d-2','d_dif','max','min','max-min']]
Y=combineddf[[numst]]

Xtrain=X[X.index<'2016-07-01']
Ytrain=Y[Y.index<'2016-07-01']

Xtest=X[(X.index>='2016-07-01')&(X.index<'2016-08-01')]
Ytest=Y[(Y.index>='2016-07-01')&(Y.index<'2016-08-01')]

#rfr=xgboost.sklearn.XGBRegressor()
rfr=GradientBoostingRegressor(max_depth=7,n_estimators=1000,verbose=1,learning_rate=0.1,random_state=1)

In [158]:
rfr.fit(Xtrain,Ytrain)
print(rfr.score(Xtrain,Ytrain))
print(rfr.score(Xtest,Ytest))

result=pd.read_excel(r'c:/users/lance/desktop/GitHub_project/tianchi_power_data/result.xlsx')

result['dow'] = result.date.apply(lambda x: x.dayofweek)
result['doy'] = result.date.apply(lambda x: x.dayofyear)
result['day'] = result.date.apply(lambda x: x.day)
result['month'] = result.date.apply(lambda x: x.month)

combinedresultdf=pd.merge(left=result,right=weatherdata,left_on='date',right_on='date',how='left')

combinedresultdf=combinedresultdf[['date','dow','doy','day','month','max','min','max-min']]

combinedresultdf['d-1']=0
combinedresultdf['d-2']=0
combinedresultdf['d_dif']=0

combinedresultdf=combinedresultdf.set_index('date')
combinedresultdf.head()
c2=combinedresultdf

c2=c2.reset_index()


c2.loc[1,'d_dif']=c2.loc[1,'d-1']-c2.loc[1,'d-2']


namelist=['dow','doy','day','month','d-1','d-2','d_dif','max','min','max-min']
c2.head()

      Iter       Train Loss   Remaining Time
         1 180791637184.0676            0.00s
         2 150274282759.2018            0.00s
         3 125544571887.6637            0.00s
         4 105050523117.3445            4.26s
         5 88717626038.7175            3.80s
         6 74830722758.2788            3.58s
         7 63248042090.9421            3.07s
         8 53803144286.6914            2.68s
         9 46304975859.6026            2.38s
        10 39817511934.8401            2.14s
        20 11468950235.2821            1.84s
        30  5325693527.2231            2.22s
        40  3073888334.3611            2.02s
        50  1893669179.1314            1.90s
        60  1248399424.3023            1.91s
        70   853945464.6789            1.83s
        80   564208653.9531            1.76s
        90   365555798.9464            1.71s
       100   232603571.0302            1.66s
       200     5829292.9954            1.68s
       300      157654.9658            1.37s
       400        6071.6659            1.18s
       500         252.3166            0.94s
       600          14.5666            0.75s
       700           0.9382            0.56s
       800           0.0447            0.37s
       900           0.0020            0.18s
      1000           0.0001            0.00s
1.0
-0.180406121478

        date  dow  doy  day  month  max  min  max-min  d-1  d-2  d_dif
0 2016-09-01    3  245    1      9   33   23       10    0    0      0
1 2016-09-02    4  246    2      9   34   22       12    0    0      0
2 2016-09-03    5  247    3      9   34   23       11    0    0      0
3 2016-09-04    6  248    4      9   31   22        9    0    0      0
4 2016-09-05    0  249    5      9   32   23        9    0    0      0

In [159]:
c2.loc[0,'d-1']=Y.loc['2016-08-31'][0]
c2.loc[0,'d-2']=Y.loc['2016-08-30'][0]
c2.loc[0,'d_dif']=c2.loc[0,'d-1']-c2.loc[0,'d-2']
c2.loc[1,'d-2']=Y.loc['2016-08-31'][0]
c2.head()

        date  dow  doy  day  month  max  min  max-min      d-1      d-2  d_dif
0 2016-09-01    3  245    1      9   33   23       10  3664003  3607667  56336
1 2016-09-02    4  246    2      9   34   22       12        0  3664003      0
2 2016-09-03    5  247    3      9   34   23       11        0        0      0
3 2016-09-04    6  248    4      9   31   22        9        0        0      0
4 2016-09-05    0  249    5      9   32   23        9        0        0      0

In [1]:
for x in range(30):
    if x!=29:
        a=rfr.predict(pd.DataFrame(c2.loc[x,namelist]).T)[0]
        c2.loc[x+1,'d-1']=a
        c2.loc[x+2,'d-2']=a
        c2.loc[x,'d_dif']=c2.loc[x,'d-1']-c2.loc[x,'d-2']
        c2.loc[x,'pre']=a
    elif x==29:
        a=rfr.predict(pd.DataFrame(c2.loc[x,namelist]).T)[0]
        c2.loc[x,'pre']=a
        c2.loc[x,'d_dif']=c2.loc[x,'d-1']-c2.loc[x,'d-2']

c2=c2[c2.index<30]
c2

NameError: name 'rfr' is not defined

In [161]:
filename=r'c:/users/lance/desktop/GitHub_project/tianchi_power_data/'+numst+r'.xlsx'
c2[['date','pre']].to_excel(filename)